#!/usr/bin/env node
const fs = require("fs")
const getopts = require("getopts")
const Processors = require("./Processors")

const opts = getopts(process.argv, {
    boolean: ["d"]
})

const [filename] = opts._.slice(2)
const contents = fs.readFileSync(filename, {encoding: "utf-8"})

if(opts.d) {
    process.stdout.write(Processors.deduplicateStringsSortRepassOut(contents))
} else {
    process.stdout.write(Processors.deduplicateStringsSortRepassIn(contents))
}