#!/usr/bin/env node
const fs = require("fs")
const getopts = require("getopts")
const DeduplicateStringsSort = require("./Processor/DeduplicateStringsSort")

const opts = getopts(process.argv, {
    boolean: ["d"]
})

const [filename] = opts._.slice(2)
const contents = fs.readFileSync(filename, {encoding: "utf-8"})

if(opts.d) {
    process.stdout.write(DeduplicateStringsSort.decode(contents))
} else {
    process.stdout.write(DeduplicateStringsSort.encode(contents))
}